# Generated by Django 3.2 on 2021-04-22 22:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(check=models.Q(price__gt=Decimal('0')), name='price_gt_0'),
        ),
    ]
