# Generated by Django 3.2 on 2021-04-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_book_price_gt_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=10),
        ),
    ]
